/* Database schema to keep the structure of entire database. */

--Create table animals
CREATE TABLE animals(
 id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 name VARCHAR(100),
 date_of_birth DATE,
 escape_attempts INT,
 neutered BOOLEAN,
 weight_kg DECIMAL
 );

--Add column species to table animals
ALTER TABLE animals ADD species VARCHAR(100);

--Create table owners
CREATE TABLE owners(
 id INT GENERATED BY DEFAULT AS IDENTITY,
 full_name VARCHAR(200),
 age INT,
 PRIMARY KEY(id)
);
