/* Database schema to keep the structure of entire database. */

--CREATE TABLE ANIMALS
CREATE TABLE animals(
 id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 name VARCHAR(100),
 date_of_birth DATE,
 escape_attempts INT,
 neutered BOOLEAN,
 weight_kg DECIMAL
 );
