/* Database schema to keep the structure of entire database. */

--Create table animals
CREATE TABLE animals(
 id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 name VARCHAR(100),
 date_of_birth DATE,
 escape_attempts INT,
 neutered BOOLEAN,
 weight_kg DECIMAL
 );

--Add column species to table animals
ALTER TABLE animals ADD species VARCHAR(100);

--Create table owners
CREATE TABLE owners(
 id INT GENERATED BY DEFAULT AS IDENTITY,
 full_name VARCHAR(200),
 age INT,
 PRIMARY KEY(id)
);

--Create table species
DROP TABLE IF EXISTS species;

CREATE TABLE species(
	id INT GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(100),
	PRIMARY KEY(id)
);

--Update table animals structure
--Remove column species
ALTER TABLE animals DROP COLUMN species;
--Add column species_id which is a foreign key referencing species table
ALTER TABLE animals ADD COLUMN species_id INT;
ALTER TABLE animals ADD CONSTRAINT species_fk FOREIGN KEY(species_id) REFERENCES species(id);
--Add column owner_id which is a foreign key referencing the owners table
ALTER TABLE animals ADD COLUMN owner_id INT;
ALTER TABLE animals ADD CONSTRAINT owners_fk FOREIGN KEY(owner_id) REFERENCES owners(id);

--Create table vets
DROP TABLE IF EXISTS vets;

CREATE TABLE vets(
 id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 name VARCHAR(200),
 age INT, 
 date_of_graduation DATE
 );
 
 --Create table specializations
DROP TABLE IF EXISTS specializations;

CREATE TABLE specializations(
 vet_id INT,
 species_id INT
);

--Add primary key to specializations
ALTER TABLE specializations ADD PRIMARY KEY(vet_id, species_id);
--Add foreign keys to specializations
ALTER TABLE specializations ADD CONSTRAINT vets_fk FOREIGN KEY(vet_id) REFERENCES vets(id);
ALTER TABLE specializations ADD CONSTRAINT species_fk FOREIGN KEY(species_id) REFERENCES species(id);

--Create table visits
DROP TABLE IF EXISTS visits;

CREATE TABLE visits(
 animal_id INT,
 vet_id INT,
 date_of_visit DATE
);

--Add foreign keys to visits
ALTER TABLE visits ADD CONSTRAINT animals_fk FOREIGN KEY(animal_id) REFERENCES animals(id);
ALTER TABLE visits ADD CONSTRAINT vets_fk FOREIGN KEY(vet_id) REFERENCES vets(id);

-- Add an email column to your owners table
ALTER TABLE owners ADD COLUMN email VARCHAR(120);
